steps:

  - label: ":build: Build"
    command: "go build ."
    plugins:
      - docker#v5.1.0:
          image: "golang:1.19"

  - label: ":test: Test"
     command: "go test -v"
    plugins:
      - docker#v5.1.0:
          image: "golang:1.19"
 
  - label: ":image: Image"
    command: docker build -t ghcr.io/damomurf/coredns-tailscale .
